service: ride-wait-trends

custom:
  tableName: ${self:service}-${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["TrendsDynamoDbTable", "Arn" ] }
  environment:
    TABLE_NAME: ${self:custom.tableName}

functions:
  retrieve:
    handler: handler.retrieve
    events:
    - schedule:
        name: ride-wait-trends-schedule-${opt:stage, self:provider.stage}
        rate: cron(0 0,14,18 * * ? *)

resources:
  Resources:
    TrendsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

